.vscode/settings.json

fix: hide .git

---

.freeCodeCamp/tooling/server.js
package-lock.json
package.json

chore: update freecodecamp-os to 1.6.1

---

.freeCodeCamp/npm/postinstall.js
.freeCodeCamp/tooling/env.js
.freeCodeCamp/tooling/git/build.js
.freeCodeCamp/tooling/git/gitterizer.js
.freeCodeCamp/tooling/hot-reload.js
.freeCodeCamp/tooling/logger.js
.freeCodeCamp/tooling/seed.js
.freeCodeCamp/tooling/server.js
.freeCodeCamp/tooling/test-utils.js
.freeCodeCamp/tooling/test.js
curriculum/locales/english/learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract.md
package-lock.json
package.json

chore: fix project 1 tests, update freecodecamp-os to 1.6.2

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/HELP.md
.vscode/settings.json
curriculum/locales/english/learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract.md
freecodecamp.conf.json

chore: finish tests, add templates, link repo

---

.github/ISSUE_TEMPLATE/BUG.md
bash/.bashrc
learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract/src/client/main.ts
tooling/camper-info.js

chore: add camper-info script

---

.freeCodeCamp/client/components/controls.tsx
.freeCodeCamp/client/components/error.tsx
.freeCodeCamp/client/components/heading.tsx
.freeCodeCamp/client/styles.css
.freeCodeCamp/client/templates/project.tsx
.freeCodeCamp/client/types/index.ts
.freeCodeCamp/tooling/lesson.js
.freeCodeCamp/tooling/parser.js
.freeCodeCamp/tooling/reset.js
.freeCodeCamp/tooling/seed.js
.freeCodeCamp/tooling/server.js
freecodecamp.conf.json
package-lock.json
package.json
tooling/camper-info.js

chore: update freecodecamp-os to 1.6.5

---

.gitpod.Dockerfile
.vscode/settings.json
Dockerfile
curriculum/locales/english/learn-how-to-interact-with-on-chain-programs.md
curriculum/locales/english/learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract.md
learn-how-to-interact-with-on-chain-programs/src/_answer/client/hello-world.js
learn-how-to-interact-with-on-chain-programs/src/_answer/client/main.js

fix: next branch updates, 2nd project improvements

---

.devcontainer/devcontainer.json
.gitpod.yml
freecodecamp.conf.json

Checklist:
Updates `freeCodeCamp - Courses` to `1.7.1`

fix(0.1.2): update courses extension to 1.7.1

---

.vscode/settings.json
build-a-smart-contract/package.json
curriculum/locales/english/learn-how-to-interact-with-on-chain-programs.md

fix: a few things for release

---

curriculum/locales/english/learn-how-to-interact-with-on-chain-programs.md
freecodecamp.conf.json

Checklist:
Closes #72
_some prettier made its way into here_

fix(0.1.3): synchronise `establishConnection`

---

package-lock.json
package.json

chore: update and audit

---

package-lock.json
package.json

Reverts freeCodeCamp/solana-curriculum#120

revert(deps): `@freecodecamp/freecodecamp-os` to `v1.8.2`

---

curriculum/locales/english/build-a-university-certification-nft.md

fix: 'acconut' typo

---

build-a-university-certification-nft/index.d.ts

fix: adjust declaration return types

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-1.md

fix: 'TickTacToe' typo

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-1.md

The actual Cargo.toml with dependencies should be the one within tic-tac-toe/programs/tic-tac-toe
Checklist:
Closes #XXXXX

fix: incorrect Cargo.toml file referenced

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

Correct variable should be 'ix'
Checklist:
Closes #XXXXX

fix: wrong variable 'tx' being checked

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: index error in checking variables

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: missing babelisedCode

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

Payer here should be playerOne instead
Checklist:
Closes #XXXXX

fix: undefined 'payer' variable

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: incorrect awaitExpression statement

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: 'extectedGameState' typo

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: use findProgramAddressSync

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: incorrect tile row

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: 'asynchroneous' typo

---

curriculum/locales/english/learn-anchor-by-building-tic-tac-toe-part-2.md

fix: incorrect error property

---

curriculum/locales/english/learn-how-to-interact-with-on-chain-programs.md
curriculum/locales/english/learn-solanas-token-program-by-minting-a-fungible-token.md

Read why, here: https://github.com/solana-labs/solana-web3.js/issues/3498

Lock to @solana/web3.js 1.x for compatibility
